# Generated by Django 4.0.5 on 2022-06-10 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='isBaja',
            field=models.BooleanField(default=False),
        ),
    ]
